name: causal_inference_final
channels:
  - conda-forge
dependencies:
  - pip=25.0.1
  - python=3.10.16
  - pip:
      - cmasher==1.9.2
      - dowhy==0.11.1
      - entsoe-py==0.6.17
      - fiona==1.9.6
      - geojson-rewind==1.1.0
      - geopandas==0.14.3
      - jupyter==1.0.0
      - numpy==1.26.4
      - openmeteo-requests==1.3.0
      - openpyxl==3.1.5
      - plotly==5.20.0
      - python-dotenv==1.0.1
      - requests-cache==1.2.1
      - retry-requests==2.0.0
      - scikit-learn==1.4.2
      - seaborn==0.13.2
